name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest  # Alterado para Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"  # Atualizado para Node.js 18, que é a versão LTS recomendada
          cache: npm

      - name: Install dependencies
        run: npm ci  # Usando npm ci para instalação limpa das dependências

      - name: Build with Next.js
        run: npm run build

      - name: Export static pages
        run: npm run export  # Adicionando comando de exportação se necessário

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out  # Certifique-se de que este é o diretório correto após o build/export

  deploy:
    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/  # Construa a URL manualmente
    runs-on: windows-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
